FROM node:22-alpine

WORKDIR /app

# install / build
COPY package*.json ./
RUN npm ci
COPY . .

# change this to be functional at some point
ENV NODE_ENV='development'

# run
EXPOSE 2567
CMD ["npm", "start"]