export enum ServerMessage {
    CONNECT = "connection",
    DISCONNECT = "disconnect",
    CREATE_GAME = "generateGame",
    JOIN_CUSTOM_GAME = "joinCustomGame",
    GAME_EXISTS = "gameExists",
    DISPLAY_JOIN = "joinAsDisplay",
    ADD_PLAYER = "addPlayer",
    PLAYER_LEAVE = "playerLeave",
    UPDATE_OPTIONS = "updateOptions",
    GAME_START = "startGame",
    BEGIN_MAROONING = "beginMarooning",
    END_MAROONING = "endMarooning",
    GEN_ROUND = "generateRound",
    ROUND_START = "roundStart",
    TIMER_TOGGLE = "toggleTimer",
    SEND_TO_VOTING = "sendToVoting",
    CAST_VOTE = "castVote",
    CLOSE_VOTING = "closeVoting",
    SEND_TO_TIEBREAK = "startTiebreak",
    TIEBREAK_VOTE = "tiebreakVoteReceived",
    VICTORY = "victory",
    SEND_TO_HOME = "sendHome",
    CLEANUP_SOCKET = "cleanupSocket"
}